global:
  scrape_interval:     2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

rule_files:
  - "alerts.yml"



scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9100" ]

  - job_name: "chat_app"
    static_configs:
      - targets: [ "host.docker.internal:2122" ]
